### ISSUE TITLE
Using hyco-ws with Webpack

### ISSUE THREAD

**Issue by shmuelzalmanov** [Azure/azure-relay-node#17]
## Actual Behavior
1. I should be able to compile

## Expected Behavior
1. I get errors related to modules and I can't compile - Module not found: Error: Can't resolve 'tls' in '..../node_modules/ws/lib'

## Versions  
- OS platform and version: Ubuntu 16.04
- Node Version: 7.0.0
- NPM package version or commit ID: 3.10.8

**Comment by dlstucki** [comment]
Does the same issue occur if you just try to use "ws" module?

**Comment by shmuelzalmanov** [comment]
Yes, here are the webpack logs ... 

WARNING in ./node_modules/ws/lib/buffer-util.js
Module not found: Error: Can't resolve 'bufferutil' in '..../node_modules/ws/lib'
 @ ./node_modules/ws/lib/buffer-util.js 56:21-42
 @ ./node_modules/ws/lib/receiver.js
 @ ./node_modules/ws/index.js
...
 @ ./src/main.js
 @ ./node_modules/aurelia-webpack-plugin/dist/aurelia-entry.js
 @ multi aurelia-webpack-plugin/dist/aurelia-entry aurelia-polyfills aurelia-loader-webpack (webpack)-dev-server/client?http://localhost:8080 aurelia-bootstrapper

WARNING in ./node_modules/ws/lib/validation.js
Module not found: Error: Can't resolve 'utf-8-validate' in '...../node_modules/ws/lib'
 @ ./node_modules/ws/lib/validation.js 4:22-47
 @ ./node_modules/ws/lib/receiver.js
 @ ./node_modules/ws/index.js
....
 @ ./src/main.js
 @ ./node_modules/aurelia-webpack-plugin/dist/aurelia-entry.js
 @ multi aurelia-webpack-plugin/dist/aurelia-entry aurelia-polyfills aurelia-loader-webpack (webpack)-dev-server/client?http://localhost:8080 aurelia-bootstrapper

ERROR in ./node_modules/ws/lib/websocket.js
Module not found: Error: Can't resolve 'net' in '...../node_modules/ws/lib'
 @ ./node_modules/ws/lib/websocket.js 7:12-26
 @ ./node_modules/ws/index.js
....
 @ ./src/main.js
 @ ./node_modules/aurelia-webpack-plugin/dist/aurelia-entry.js
 @ multi aurelia-webpack-plugin/dist/aurelia-entry aurelia-polyfills aurelia-loader-webpack (webpack)-dev-server/client?http://localhost:8080 aurelia-bootstrapper

ERROR in ./node_modules/ws/lib/websocket.js
Module not found: Error: Can't resolve 'tls' in '..../node_modules/ws/lib'
 @ ./node_modules/ws/lib/websocket.js 8:12-26
 @ ./node_modules/ws/index.js
...
 @ ./src/main.js
 @ ./node_modules/aurelia-webpack-plugin/dist/aurelia-entry.js
 @ multi aurelia-webpack-plugin/dist/aurelia-entry aurelia-polyfills aurelia-loader-webpack (webpack)-dev-server/client?http://localhost:8080 aurelia-bootstrapper

**Comment by dlstucki** [comment]
Is this other thread applicable?

https://github.com/krasimir/webpack-library-starter/issues/6#issuecomment-256219200

"calebissharp commented on Oct 25 2016 
The 'ws' library cannot be used in a browser context. You have to use WebSockets API directly (https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API)."
