### ISSUE TITLE
Cannot find module 'wait.for'

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-relay-node#4]
When trying to run [websocket ](https://github.com/Azure/azure-relay-node/tree/master/examples/hyco-websocket-simple) sample , getting following error:

Error: Cannot find module 'wait.for'
   at Module._resolveFilename (module.js:351:5)
   at Module._load (module.js:300:3)
   at Module.prototype.require (module.js:377:3)
   at require (internal/module.js:16:7)
...

Before start, I added following (the only one) dependency in package.json
  "dependencies": {
     "hyco-websocket":"latest"
  }

After getting the error shown above, I added  missing package:
  "dependencies": {
     "hyco-websocket":"latest",
      "wait.for" : "latest"
  },

And finally getting this error:
...
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\***\AppData\Local\Programs\Python\Python35-32", you can set the PYTHON env variable.
gyp ERR! stack    at failNoPython (C:\Program Files\nodejs (chakracore)\node_modules\npm\node_modules\node-gyp\lib\configure.js:117:5)
gyp ERR! stack    at Anonymous function (C:\Program Files\nodejs (chakracore)\node_modules\npm\node_modules\node-gyp\lib\configure.js:72:11)
gyp ERR! stack    at Anonymous function (fs.js:82:5)
gyp ERR! System Windows_NT 10.0.14393
...

**Comment by jtaubensee** [comment]
@ddobric - Thanks for bringing this up. In the meantime just wanted to make sure that you were able to get the hyco-ws sample up and running?

https://github.com/Azure/azure-relay-node/tree/master/hyco-ws

https://docs.microsoft.com/en-us/azure/service-bus-relay/relay-hybrid-connections-node-get-started

**Comment by clemensv** [comment]
Confirmed bug. Will fix.

**Comment by clemensv** [comment]
Fix checked in. Will push the NPM update later today.

**Comment by jtaubensee** [comment]
FYI - 2e4e54d is the commit with the fix.
