### ISSUE TITLE
Build fails because /lib/_hyco_errors references an unknown module.

### ISSUE THREAD

**Issue by mikewalpole-systemc** [Azure/azure-relay-node#40]
## Actual Behavior
1. The build of our product fails when we include hyco-https as a dependency because the bundling process tries to resolve all module references in the dependencies. File '_hyco_errors.js' has a reference to 'internal/util', which doesn't exist - I assume this is meant to represent the NodeJs 'util' module.
2. The code in _hyco_errors.js which would try to load 'internal/util' appears to be not referenced anywhere else in hyco-https. I can work around this by registering 'internal/util' as an alias to be resolved by Webpack, but this seems like the wrong solution.

## Expected Behavior
1. The reference to the unresolved module is removed from _hyco_errors.js, and the apparently redundant code removed - or should the reference actually be to 'util' rather than 'internal/util' (there are references to just 'util' elsewhere)?

## Versions  
- Windows10
- Node Version: v10.16.3
- NPM package version or commit ID: v1.4.1

**Comment by bainian12345** [comment]
Removed the dependency in 1.4.2
