### ISSUE TITLE
Trouble connecting

### ISSUE THREAD

**Issue by khowling** [Azure/azure-relay-node#5]
I've created a hybrid connection in Azure portal, and the connection string i get is : 

Endpoint=hc://mynamespace01.hybrid.biztalk.windows.net/laptop;SharedAccessKeyName=defaultSender;SharedAccessKey=xxxx

how do i get the example listener to connect? 

> node listener.js mynamespace01.hybrid.biztalk.windows.net laptop defaultSender xxxx

gives: 

errorError: getaddrinfo ENOTFOUND

**Comment by dstuckims** [comment]
It looks like you're trying to mix BizTalk Hybrid Connections (V1) with the new Azure Relay Hybrid Connections (v2).  Ensure you create your Hybrid Connection in the Azure Portal inside a Relay Namespace.

Portal Uri would look something like (note the "Microsoft.Relay"):
https://ms.portal.azure.com/#blade/HubsExtension/Resources/resourceType/Microsoft.Relay%2Fnamespaces

The connection string should look like (note the Endpoint has a scheme of "sb://"):
Endpoint=sb://mynamespace.**servicebus.windows.net**/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=....
